# Page settings

baseURL = "https://jose-oc.github.io/cv/"
languageCode = "en-us"
title = "Jose Ortiz - CV"
theme = "hugo-orbit-theme"
# googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableKinds=["404", "RSS", "sitemap"]

# To build the project into this folder (docs is the one used by github to create the static website)
publishDir = "docs"

[params]

# Meta
    description = "Jose Ortiz devops/platform engineer"
    author = "Jose Ortiz"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Jose Ortiz"
        tagline = "DevOps/Platform Engineer"
        avatar = "profile.png"

    # Contact section
    [params.contact]
        enable = true

#        [[params.contact.list]]
#        class = "email"
#        icon = "fa-envelope"
#        url = "mailto:@gmail.com"
#        title = "@gmail.com"

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: jose.oc+developer@gmail.com"
        title = "jose.oc@gmail.com"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+1234567890"
        # title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//joseoc.com"
        title = "joseoc.com"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/joseoc"
        title = "linkedin.com/in/joseoc"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/jose-oc"
        title = "github.com/jose-oc"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/_jose_oc"
        title = "@_jose_oc"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Bachelor's Degree in Computer Engineering"
        college = "University of Málaga"
        #dates = "2000 - 2005"

        [[params.education.list]]
        degree = "Master's Degree in Secondary Education"
        college = "University of Málaga"
        #dates = "2011 - 2012"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "English"
        level = "B2"

        [[params.language.list]]
        language = "Spanish"
        level = "Native"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Education"

        [[params.interests.list]]
        interest = "Music"

        [[params.interests.list]]
        interest = "Photography"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "20+ years working in It, working the latest 5 as DevOps Engineer building automation, cloud infrastructure, and Python-based tooling for scalable, reliable systems. Bridges development and operations by creating CLI tools, Lambda functions, and CI/CD integrations that simplify workflows and eliminate manual steps. Experienced with AWS, Kubernetes, Terraform, Ansible, and Python — passionate about automating everything from infrastructure provisioning to documentation generation."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "DevOps / Platform Engineer"
        dates = "Nov 2022 - Present"
        company = "NEP Group, Málaga (Spain)"
        details = "Automated deployment and configuration of infrastructure and observability stacks on Kubernetes using Ansible, reducing setup time from days to under an hour. Developed Python scripts integrated into GitHub Actions to sync Docker images and Helm charts with a private Google Artifact Registry, ensuring reliable artifact availability. Created Python CLI tools to automate internal workflows: syncing Ansible inventory with 1Password and generating scaffolding. Generating Confluence documentation from HTML templates and inventory variables. Designed and implemented cost-optimization automation for AWS (EC2, ECS, RDS, and Lambda): instance rightsizing, spot-instance usage, automated environment startup/shutdown. Built runbooks for recurring incidents, improving on-call efficiency and response consistency. Managed 30+ distributed datacenters, each with multiple Kubernetes nodes and VMs, ensuring observability and stability across all environments."

        [[params.jobs.list]]
        position = "Lead Developer / DevOps Engineer"
        dates = "Mar 2015 - Nov 2022"
        company = "Piksel Inc, Málaga (Spain)"
        details = "Led a cross-functional team of six developers and DevOps engineers building a distributed Python-based workflow platform (similar to N8N) to process large-scale media workloads on AWS. Designed modular Python libraries for transcoding videos, generating metadata, processing subtitles, and analyzing video content — connected via standardized inputs/outputs for composable workflows. Used pytest for testing, boto3 for AWS interactions, and Terraform for infrastructure provisioning. Developed a Lambda function to manage AWS RDS startup/shutdown via schedule or manual triggers from GoCD pipelines, optimizing costs and reducing idle usage. Created and maintained Terraform CI/CD pipelines using GoCD and GitLab CI for continuous infrastructure delivery. Collaborated with developers to integrate observability and logging, leveraging ElasticSearch/Kibana for debugging and performance insights. Achieved 15% operational cost reduction by automating provisioning and improving resource utilization."

        [[params.jobs.list]]
        position = "Software Developer / Backend Engineer"
        dates = "Earlier experience"
        company = "Various companies"
        details = "Worked as a software developer and backend engineer across multiple projects using Java, Python, and PHP. Developed enterprise and web systems for clients in media and education sectors, gaining a strong foundation in clean coding and system design."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "Selected projects from my professional experience."

        [[params.projects.list]]
        title = "CI/CD + Python Integration"
        tagline = "GitHub Actions automation to manage internal registries, including syncing Docker images and Helm charts with a private Google Artifact Registry."

        [[params.projects.list]]
        title = "AWS Cost Optimization"
        tagline = "Python Lambda functions and Terraform pipelines for dynamic resource control, including instance rightsizing, spot-instance usage, and automated environment startup/shutdown."

        [[params.projects.list]]
        title = "Infrastructure Automation"
        tagline = "Ansible-driven stack deployments (Proxmox, Talos, Grafana, Loki, MinIO) with retention and user policies, reducing setup time from days to under an hour."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "DevOps & Cloud"
        level = "AWS (EC2, Batch, Lambda, RDS, Dynamo, S3, IAM), Kubernetes (K3s, Talos, GKE), VMware, Proxmox"

        [[params.skills.list]]
        skill = "Python Development & Automation"
        level = "CLI tools, AWS Boto3, Jinja2 templating, pytest, REST integrations, automation scripts"

        [[params.skills.list]]
        skill = "IaC & CI/CD"
        level = "Terraform, Ansible, Packer, GitLab CI, GitHub Actions, GoCD pipelines"

        [[params.skills.list]]
        skill = "Observability & Ops"
        level = "Grafana, Loki, InfluxDB, Promtail, log management, retention policies, performance tuning"

        [[params.skills.list]]
        skill = "Soft Skills"
        level = "Analytical mindset, strong documentation habits, collaborative problem solver"


    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    # 
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
    	copyright = ""
        #copyright = "2017 © Ported for Jose by Pavel Kanyshev"