baseURL = "http://cv.joseoc.com/"
languageCode = "en-us"
title = "Jose Ortiz - CV"

theme = "hugo-orbit-theme"

# To build the project into this folder (docs is the one used by github to create the static website)
publishDir = "docs"

